import { processSurfaceDefinitionSchema } from './model.ts'

export const processPlantUnitOverviewSurface = processSurfaceDefinitionSchema.parse({
  schemaVersion: 1,
  id: 'unit-overview',
  title: 'Unit Overview',
  description: 'First-order process overview for one process-plant unit.',
  designSize: { width: 1600, height: 900 },
  regions: [
    { id: 'unit-status', label: 'Unit status', role: 'unit-status', order: 0 },
    { id: 'primary', label: 'Primary system', role: 'primary-system', order: 1 },
    { id: 'heat-transfer', label: 'Steam generators', role: 'heat-transfer', order: 2 },
    { id: 'secondary', label: 'Secondary system', role: 'secondary-system', order: 3 },
    { id: 'support', label: 'Support systems', role: 'support-system', order: 4 },
    { id: 'alarms', label: 'Alarms', role: 'alarms', order: 5 },
  ],
  widgets: [
    {
      id: 'unit-status-banner',
      type: 'statusBanner',
      label: 'Unit status',
      region: 'unit-status',
      rank: 0,
      binds: {
        thermalPower: { label: 'Thermal power', path: 'core.totalThermalPowerMw', digits: 0 },
        electricOutput: { label: 'Electric output', path: 'turbine.electricMw', digits: 0 },
        reactivity: { label: 'Reactivity', path: 'core.effectiveReactivityPcm', digits: 0 },
      },
    },
    {
      id: 'reactor-vessel',
      type: 'vessel',
      label: 'Reactor Vessel',
      region: 'primary',
      source: { componentIds: ['core', 'vessel'] },
      role: 'reactor-vessel',
      rank: 0,
      binds: {
        level: { label: 'Inventory', path: 'vessel.primaryCoolantInventoryKg', digits: 0 },
        pressure: { label: 'Pressure', path: 'pressurizer.pressureMPa', digits: 2 },
        temperature: { label: 'Coolant temp', path: 'vessel.meanPrimaryCoolantTemperatureC', digits: 0 },
      },
      ports: { hotLegA: 'right', coldLegA: 'left' },
    },
    {
      id: 'pressurizer',
      type: 'vessel',
      label: 'Pressurizer',
      region: 'primary',
      source: { componentIds: ['pressurizer'] },
      role: 'pressurizer',
      rank: 1,
      binds: {
        level: { label: 'Level', path: 'pressurizer.levelPercent', digits: 0, display: 'percent' },
        pressure: { label: 'Pressure', path: 'pressurizer.pressureMPa', digits: 2 },
        relief: { label: 'Relief flow', path: 'pressurizer.reliefFlowKgPerS', digits: 1 },
      },
      ports: { surgeLine: 'bottom' },
    },
    {
      id: 'rcp-a',
      type: 'pump',
      label: 'RCP A',
      region: 'primary',
      source: { componentIds: ['rcpA'] },
      role: 'reactor-coolant-pump',
      rank: 2,
      binds: {
        speed: { label: 'Speed', path: 'rcpA.speedFraction', digits: 2, display: 'percent' },
        flow: { label: 'Loop flow', path: 'rcs-hot-leg-a.flowKgPerS', digits: 0 },
      },
      ports: { inlet: 'left', outlet: 'right' },
    },
    {
      id: 'sg-a',
      type: 'heatExchanger',
      label: 'Steam Generator A',
      region: 'heat-transfer',
      source: { componentIds: ['sgA'] },
      role: 'steam-generator',
      rank: 0,
      binds: {
        level: { label: 'Level', path: 'sgA.levelPercent', digits: 0, display: 'percent' },
        pressure: { label: 'Pressure', path: 'sgA.pressureMPa', digits: 2 },
        steam: { label: 'Steam flow', path: 'sg-a-steam-to-msiv-a.flowKgPerS', digits: 0 },
        radiation: { label: 'Radiation', path: 'sgA.secondaryRadiationMSvPerH', digits: 2 },
      },
      ports: { primaryIn: 'left', primaryOut: 'left', steamOut: 'right', feedwaterIn: 'bottom' },
    },
    {
      id: 'sg-b',
      type: 'heatExchanger',
      label: 'Steam Generator B',
      region: 'heat-transfer',
      source: { componentIds: ['sgB'] },
      role: 'steam-generator',
      rank: 1,
      binds: {
        level: { label: 'Level', path: 'sgB.levelPercent', digits: 0, display: 'percent' },
        pressure: { label: 'Pressure', path: 'sgB.pressureMPa', digits: 2 },
        steam: { label: 'Steam flow', path: 'sg-b-steam-to-msiv-b.flowKgPerS', digits: 0 },
        radiation: { label: 'Radiation', path: 'sgB.secondaryRadiationMSvPerH', digits: 2 },
      },
      ports: { primaryIn: 'left', primaryOut: 'left', steamOut: 'right', feedwaterIn: 'bottom' },
    },
    {
      id: 'turbine',
      type: 'pump',
      label: 'Turbine Generator',
      region: 'secondary',
      source: { componentIds: ['turbine'] },
      role: 'turbine-generator',
      rank: 0,
      binds: {
        output: { label: 'Output', path: 'turbine.electricMw', digits: 0 },
        steam: { label: 'Steam use', path: 'turbine.steamFlowKgPerS', digits: 0 },
      },
      ports: { steamIn: 'left', exhaust: 'bottom' },
      style: { tone: 'secondary' },
    },
    {
      id: 'condenser',
      type: 'vessel',
      label: 'Condenser',
      region: 'secondary',
      source: { componentIds: ['condenser'] },
      role: 'condenser',
      rank: 1,
      binds: {
        level: { label: 'Hotwell', path: 'condenser.condensateLevelPercent', digits: 0, display: 'percent' },
        backPressure: { label: 'Backpressure', path: 'condenser.backPressurePa', digits: 0 },
        heatRejected: { label: 'Heat rejected', path: 'condenser.heatRejectedMw', digits: 0 },
      },
      ports: { steamIn: 'top', condensateOut: 'bottom' },
      style: { tone: 'secondary' },
    },
    {
      id: 'feedwater',
      type: 'vessel',
      label: 'Feedwater Tank',
      region: 'support',
      source: { componentIds: ['feedwaterTank'] },
      role: 'feedwater',
      rank: 0,
      binds: {
        level: { label: 'Level', path: 'feedwaterTank.levelPercent', digits: 0, display: 'percent' },
        flow: { label: 'Available flow', path: 'feedwaterTank.availableOutletFlowKgPerS', digits: 0 },
      },
      ports: { outlet: 'top' },
      style: { tone: 'support' },
    },
    {
      id: 'electrical',
      type: 'numericReadout',
      label: 'Electrical Buses',
      region: 'support',
      role: 'electrical',
      rank: 1,
      binds: {
        busA: { label: 'Safety Bus A', path: 'safetyBusA.voltageFraction', digits: 2, display: 'percent' },
        busB: { label: 'Safety Bus B', path: 'safetyBusB.voltageFraction', digits: 2, display: 'percent' },
      },
      style: { tone: 'support' },
    },
    {
      id: 'alarm-strip',
      type: 'alarmStrip',
      label: 'Alarm summary',
      region: 'alarms',
      rank: 0,
      binds: {
        containmentPressure: { label: 'Containment', path: 'containment.pressureMPa', digits: 3 },
        sgARadiation: { label: 'SG A radiation', path: 'sgA.secondaryRadiationMSvPerH', digits: 2 },
      },
      style: { tone: 'warning' },
    },
  ],
  paths: [
    {
      id: 'primary-hot-leg-a',
      label: 'Primary hot leg',
      source: { connectionId: 'rcs-hot-leg-a' },
      from: 'reactor-vessel.hotLegA',
      to: 'sg-a.primaryIn',
      binds: { flow: { label: 'Flow', path: 'rcs-hot-leg-a.flowKgPerS', digits: 0 } },
      style: { service: 'primary' },
    },
    {
      id: 'main-steam-to-turbine',
      label: 'Main steam',
      from: 'sg-a.steamOut',
      to: 'turbine.steamIn',
      binds: { flow: { label: 'Flow', path: 'main-steam-header-to-turbine-stop-valve.flowKgPerS', digits: 0 } },
      style: { service: 'steam' },
    },
    {
      id: 'turbine-exhaust-to-condenser',
      label: 'Turbine exhaust',
      source: { connectionId: 'turbine-exhaust-to-condenser' },
      from: 'turbine.exhaust',
      to: 'condenser.steamIn',
      binds: { flow: { label: 'Flow', path: 'turbine-exhaust-to-condenser.flowKgPerS', digits: 0 } },
      style: { service: 'steam' },
    },
    {
      id: 'feedwater-to-sg-a',
      label: 'Feedwater',
      from: 'feedwater.outlet',
      to: 'sg-a.feedwaterIn',
      binds: { flow: { label: 'Flow', path: 'feedwater-control-valve-a-to-sg-a.flowKgPerS', digits: 0 } },
      style: { service: 'feedwater' },
    },
  ],
})

export const processPlantReferenceSurfaces = [processPlantUnitOverviewSurface] as const
