import { z } from 'zod'
import type { ComponentDefinition, ComponentKind } from './model.ts'
import { defineComponent, normalized, variable } from './component-definition-helpers.ts'

export const steamGeneratorComponentDefinitions: ReadonlyArray<ComponentDefinition> = [
  defineComponent({
    kind: 'steamGenerator' as ComponentKind,
    label: 'Steam Generator',
    ports: {
      primaryInlet: { kind: 'hydraulicThermal', direction: 'in' },
      primaryOutlet: { kind: 'hydraulicThermal', direction: 'out' },
      feedwaterInlet: { kind: 'hydraulicThermal', direction: 'in' },
      steamOutlet: { kind: 'steam', direction: 'out' },
      isolationSignal: { kind: 'logicSignal', direction: 'in' },
    },
    parametersSchema: z.object({
      nominalPressureMPa: z.number().finite().positive(),
      nominalLevelPercent: normalized,
      heatTransferCoefficientMwPerK: z.number().finite().positive(),
      initialPrimaryInletTemperatureC: z.number().finite().optional(),
      initialPrimaryOutletTemperatureC: z.number().finite().optional(),
      initialSecondaryTemperatureC: z.number().finite().optional(),
      nominalSecondaryInventoryKg: z.number().finite().positive().optional(),
      nominalSteamFlowKgPerS: z.number().finite().positive().optional(),
      initialSteamFlowFraction: normalized.optional(),
      recirculationRatio: z.number().finite().positive().optional(),
      primaryThermalTimeConstantS: z.number().finite().positive().optional(),
      secondaryThermalTimeConstantS: z.number().finite().positive().optional(),
      steamQualityTimeConstantS: z.number().finite().positive().optional(),
      steamPressureGainMPaPerKgS: z.number().finite().nonnegative().optional(),
      steamMassPressureGainFraction: z.number().finite().nonnegative().optional(),
      temperaturePressureGainFraction: z.number().finite().nonnegative().optional(),
      nominalSteamMassKg: z.number().finite().positive().optional(),
      voidFractionAtNominalBoiling: normalized.optional(),
      voidFractionTimeConstantS: z.number().finite().positive().optional(),
      swellLevelGainPercent: z.number().finite().nonnegative().optional(),
      tubeBundleBottomLevelPercent: normalized.optional(),
      tubeBundleTopLevelPercent: normalized.optional(),
      minimumUncoveredTubeHeatTransferFraction: normalized.optional(),
      pressureInventoryGainMPaPerFraction: z.number().finite().nonnegative().optional(),
      tubeMetalThermalCapacityMjPerK: z.number().finite().positive().optional(),
      tubeMetalInitialTemperatureC: z.number().finite().optional(),
      tubeLeakFlowCoefficientKgPerSPerSqrtMPa: z.number().finite().nonnegative().optional(),
      tubeLeakRadiationGainMSvPerHPerKgS: z.number().finite().nonnegative().optional(),
      tubeLeakRadiationTimeConstantS: z.number().finite().positive().optional(),
    }),
    variables: [
      variable({ path: 'levelPercent', label: 'Steam generator level', kind: 'state', discipline: 'hydraulic', writable: false, publish: 'telemetry', quantity: 'ratio', unit: 'percent' }),
      variable({ path: 'pressureMPa', label: 'Steam generator pressure', kind: 'state', discipline: 'thermal', writable: false, publish: 'telemetry', quantity: 'pressure', unit: 'MPa' }),
      variable({ path: 'heatTransferMw', label: 'Heat transfer', kind: 'derived', discipline: 'thermal', writable: false, publish: 'telemetry', quantity: 'power', unit: 'MW' }),
      variable({ path: 'primaryInletTemperatureC', label: 'Primary inlet temperature', kind: 'state', discipline: 'thermal', writable: false, publish: 'telemetry', quantity: 'temperature', unit: 'degC' }),
      variable({ path: 'primaryOutletTemperatureC', label: 'Primary outlet temperature', kind: 'state', discipline: 'thermal', writable: false, publish: 'telemetry', quantity: 'temperature', unit: 'degC' }),
      variable({ path: 'tubeMetalTemperatureC', label: 'Tube metal temperature', kind: 'state', discipline: 'thermal', writable: false, publish: 'telemetry', quantity: 'temperature', unit: 'degC' }),
      variable({ path: 'secondaryTemperatureC', label: 'Secondary temperature', kind: 'state', discipline: 'thermal', writable: false, publish: 'telemetry', quantity: 'temperature', unit: 'degC' }),
      variable({ path: 'steamFlowKgPerS', label: 'Steam production', kind: 'derived', discipline: 'hydraulic', writable: false, publish: 'telemetry', quantity: 'flowRate', unit: 'kg/s' }),
      variable({ path: 'boilingRateKgPerS', label: 'Secondary boiling rate', kind: 'derived', discipline: 'hydraulic', writable: false, publish: 'telemetry', quantity: 'flowRate', unit: 'kg/s' }),
      variable({ path: 'feedwaterFlowKgPerS', label: 'Feedwater inflow', kind: 'derived', discipline: 'hydraulic', writable: false, publish: 'telemetry', quantity: 'flowRate', unit: 'kg/s' }),
      variable({ path: 'steamOutflowKgPerS', label: 'Steam outlet flow', kind: 'derived', discipline: 'hydraulic', writable: false, publish: 'telemetry', quantity: 'flowRate', unit: 'kg/s' }),
      variable({ path: 'steamQualityFraction', label: 'Steam quality', kind: 'derived', discipline: 'thermal', writable: false, publish: 'telemetry', quantity: 'ratio', unit: 'fraction' }),
      variable({ path: 'secondaryInventoryKg', label: 'Secondary inventory', kind: 'state', discipline: 'hydraulic', writable: false, publish: 'telemetry', quantity: 'mass', unit: 'kg' }),
      variable({ path: 'collapsedLevelPercent', label: 'Collapsed water level', kind: 'state', discipline: 'hydraulic', writable: false, publish: 'telemetry', quantity: 'ratio', unit: 'percent' }),
      variable({ path: 'voidFraction', label: 'Secondary void fraction', kind: 'state', discipline: 'thermal', writable: false, publish: 'telemetry', quantity: 'ratio', unit: 'fraction' }),
      variable({ path: 'swellLevelPercent', label: 'Void swell level contribution', kind: 'derived', discipline: 'hydraulic', writable: false, publish: 'telemetry', quantity: 'ratio', unit: 'percent' }),
      variable({ path: 'tubeCoverageFraction', label: 'Steam generator tube coverage', kind: 'derived', discipline: 'hydraulic', writable: false, publish: 'telemetry', quantity: 'ratio', unit: 'fraction' }),
      variable({ path: 'tubeUncoveredFraction', label: 'Steam generator uncovered tube fraction', kind: 'derived', discipline: 'hydraulic', writable: false, publish: 'telemetry', quantity: 'ratio', unit: 'fraction' }),
      variable({ path: 'availableHeatTransferFraction', label: 'Available steam generator heat transfer fraction', kind: 'derived', discipline: 'thermal', writable: false, publish: 'telemetry', quantity: 'ratio', unit: 'fraction' }),
      variable({ path: 'steamMassKg', label: 'Steam space mass proxy', kind: 'state', discipline: 'thermal', writable: false, publish: 'telemetry', quantity: 'mass', unit: 'kg' }),
      variable({ path: 'pressureTargetMPa', label: 'Steam generator pressure target', kind: 'derived', discipline: 'thermal', writable: false, publish: 'telemetry', quantity: 'pressure', unit: 'MPa' }),
      variable({ path: 'steamMassPressureBiasMPa', label: 'Steam mass pressure contribution', kind: 'derived', discipline: 'thermal', writable: false, publish: 'telemetry', quantity: 'pressureDelta', unit: 'MPa' }),
      variable({ path: 'temperaturePressureBiasMPa', label: 'Secondary temperature pressure contribution', kind: 'derived', discipline: 'thermal', writable: false, publish: 'telemetry', quantity: 'pressureDelta', unit: 'MPa' }),
      variable({ path: 'inventoryPressureBiasMPa', label: 'Secondary inventory pressure contribution', kind: 'derived', discipline: 'thermal', writable: false, publish: 'telemetry', quantity: 'pressureDelta', unit: 'MPa' }),
      variable({ path: 'secondaryInventoryBalanceResidualKg', label: 'Secondary inventory balance residual', kind: 'derived', discipline: 'hydraulic', writable: false, publish: 'telemetry', quantity: 'massDelta', unit: 'kg' }),
      variable({ path: 'steamMassBalanceResidualKg', label: 'Steam mass balance residual', kind: 'derived', discipline: 'hydraulic', writable: false, publish: 'telemetry', quantity: 'massDelta', unit: 'kg' }),
      variable({ path: 'boilingEnergyResidualMw', label: 'Boiling energy balance residual', kind: 'derived', discipline: 'thermal', writable: false, publish: 'telemetry', quantity: 'powerDelta', unit: 'MW' }),
      variable({ path: 'tubeLeakFraction', label: 'Tube leak fraction', kind: 'control', discipline: 'control', writable: true, publish: 'telemetry', quantity: 'ratio', unit: 'fraction' }),
      variable({ path: 'primaryToSecondaryLeakKgPerS', label: 'Primary-to-secondary leak flow', kind: 'derived', discipline: 'hydraulic', writable: false, publish: 'telemetry', quantity: 'flowRate', unit: 'kg/s' }),
      variable({ path: 'secondaryRadiationMSvPerH', label: 'Secondary radiation', kind: 'derived', discipline: 'radiological', writable: false, publish: 'telemetry', quantity: 'radiationDoseRate', unit: 'mSv/h' }),
    ],
  }),
]
