import { z } from 'zod'
import type { ComponentDefinition, ComponentKind, ComponentVariableDescriptor, LocalVariablePath } from './model.ts'
import { componentVariableDescriptorSchema } from './model.ts'

const normalized = z.number().finite().min(0).max(1)

type ComponentVariableInput = Omit<ComponentVariableDescriptor, 'path'> & {
  readonly path: string
}

const variable = (descriptor: ComponentVariableInput): ComponentVariableDescriptor => ({
  ...componentVariableDescriptorSchema.parse(descriptor),
  path: descriptor.path as LocalVariablePath,
})

export const defineComponent = (definition: ComponentDefinition): ComponentDefinition => definition

const topologyComponent = (
  kind: string,
  label: string,
  ports: ComponentDefinition['ports'],
): ComponentDefinition => defineComponent({
  kind: kind as ComponentKind,
  label,
  ports,
  parametersSchema: z.object({}).strict(),
  variables: [],
})

const headerVariables = (labelPrefix: string): ReadonlyArray<ComponentVariableDescriptor> => [
  variable({ path: 'inletFlowKgPerS', label: `${labelPrefix} inlet flow`, kind: 'derived', domain: 'hydraulic', writable: false, publish: 'telemetry', quantity: 'flowRate', unit: 'kg/s' }),
  variable({ path: 'outletFlowKgPerS', label: `${labelPrefix} outlet flow`, kind: 'derived', domain: 'hydraulic', writable: false, publish: 'telemetry', quantity: 'flowRate', unit: 'kg/s' }),
  variable({ path: 'flowBalanceResidualKgPerS', label: `${labelPrefix} flow balance residual`, kind: 'derived', domain: 'hydraulic', writable: false, publish: 'telemetry', quantity: 'flowRateDelta', unit: 'kg/s' }),
  variable({ path: 'mixedTemperatureC', label: `${labelPrefix} mixed temperature`, kind: 'derived', domain: 'thermal', writable: false, publish: 'telemetry', quantity: 'temperature', unit: 'degC' }),
  variable({ path: 'mixedPressureMPa', label: `${labelPrefix} mixed pressure`, kind: 'derived', domain: 'thermal', writable: false, publish: 'telemetry', quantity: 'pressure', unit: 'MPa' }),
]

const valveVariables = (labelPrefix: string): ReadonlyArray<ComponentVariableDescriptor> => [
  variable({ path: 'positionFraction', label: `${labelPrefix} position`, kind: 'control', domain: 'control', writable: true, publish: 'telemetry', quantity: 'ratio', unit: 'fraction' }),
  variable({ path: 'effectivePositionFraction', label: `${labelPrefix} effective position`, kind: 'derived', domain: 'control', writable: false, publish: 'telemetry', quantity: 'ratio', unit: 'fraction' }),
  variable({ path: 'inletFlowKgPerS', label: `${labelPrefix} inlet flow`, kind: 'derived', domain: 'hydraulic', writable: false, publish: 'telemetry', quantity: 'flowRate', unit: 'kg/s' }),
  variable({ path: 'outletFlowKgPerS', label: `${labelPrefix} outlet flow`, kind: 'derived', domain: 'hydraulic', writable: false, publish: 'telemetry', quantity: 'flowRate', unit: 'kg/s' }),
  variable({ path: 'flowBalanceResidualKgPerS', label: `${labelPrefix} flow balance residual`, kind: 'derived', domain: 'hydraulic', writable: false, publish: 'telemetry', quantity: 'flowRateDelta', unit: 'kg/s' }),
]

const processPlantComponentDefinitions: ReadonlyArray<ComponentDefinition> = [
  defineComponent({
    kind: 'reactorCore' as ComponentKind,
    label: 'Reactor Core',
    ports: {
      hotLegA: { kind: 'hydraulicThermal', direction: 'out' },
      hotLegB: { kind: 'hydraulicThermal', direction: 'out' },
      hotLegC: { kind: 'hydraulicThermal', direction: 'out' },
      hotLegD: { kind: 'hydraulicThermal', direction: 'out' },
      coldLegA: { kind: 'hydraulicThermal', direction: 'in' },
      coldLegB: { kind: 'hydraulicThermal', direction: 'in' },
      coldLegC: { kind: 'hydraulicThermal', direction: 'in' },
      coldLegD: { kind: 'hydraulicThermal', direction: 'in' },
      vesselThermal: { kind: 'thermal', direction: 'out' },
      rodDemand: { kind: 'controlSignal', direction: 'in' },
      tripSignal: { kind: 'logicSignal', direction: 'in' },
    },
    parametersSchema: z.object({
      ratedPowerMw: z.number().finite().positive(),
      initialPowerFraction: normalized,
      initialCoolantInletTemperatureC: z.number().finite().optional(),
      coolantThermalTimeConstantS: z.number().finite().positive().optional(),
      fuelThermalTimeConstantS: z.number().finite().positive().optional(),
      fuelTemperatureRiseAtRatedPowerC: z.number().finite().positive().optional(),
      decayHeatFractionAtPower: z.number().finite().min(0).max(0.2).optional(),
      decayHeatTimeConstantS: z.number().finite().positive().optional(),
      referenceCoolantOutletTemperatureC: z.number().finite().optional(),
      referenceFuelTemperatureC: z.number().finite().optional(),
      coolantTemperatureFeedbackPcmPerC: z.number().finite().optional(),
      fuelTemperatureFeedbackPcmPerC: z.number().finite().optional(),
      criticalRodInsertionFraction: normalized.optional(),
      rodWorthPcm: z.number().finite().positive().optional(),
      kineticsPcmPerEfoldPerSecond: z.number().finite().positive().optional(),
      maxPowerRampFractionPerS: z.number().finite().positive().optional(),
      fuelThermalCapacityMjPerC: z.number().finite().positive(),
    }),
    variables: [
      variable({ path: 'powerMw', label: 'Core fission power', kind: 'state', domain: 'nuclear', writable: false, publish: 'telemetry', quantity: 'power', unit: 'MW' }),
      variable({ path: 'fissionPowerMw', label: 'Core fission power diagnostic', kind: 'derived', domain: 'nuclear', writable: false, publish: 'telemetry', quantity: 'power', unit: 'MW' }),
      variable({ path: 'totalThermalPowerMw', label: 'Core total thermal power', kind: 'derived', domain: 'thermal', writable: false, publish: 'telemetry', quantity: 'power', unit: 'MW' }),
      variable({ path: 'reactivityPcm', label: 'Reactivity', kind: 'state', domain: 'nuclear', writable: false, publish: 'telemetry', quantity: 'reactivity', unit: 'pcm' }),
      variable({ path: 'promptReactivityPcm', label: 'Rod-programmed reactivity', kind: 'derived', domain: 'nuclear', writable: false, publish: 'telemetry', quantity: 'reactivity', unit: 'pcm' }),
      variable({ path: 'temperatureFeedbackPcm', label: 'Temperature feedback reactivity', kind: 'derived', domain: 'nuclear', writable: false, publish: 'telemetry', quantity: 'reactivity', unit: 'pcm' }),
      variable({ path: 'effectiveReactivityPcm', label: 'Effective core reactivity', kind: 'derived', domain: 'nuclear', writable: false, publish: 'telemetry', quantity: 'reactivity', unit: 'pcm' }),
      variable({ path: 'rodInsertionFraction', label: 'Rod insertion', kind: 'control', domain: 'control', writable: true, publish: 'telemetry', quantity: 'ratio', unit: 'fraction' }),
      variable({ path: 'coolantInletTemperatureC', label: 'Core coolant inlet temperature', kind: 'state', domain: 'thermal', writable: false, publish: 'telemetry', quantity: 'temperature', unit: 'degC' }),
      variable({ path: 'coolantOutletTemperatureC', label: 'Core coolant outlet temperature', kind: 'state', domain: 'thermal', writable: false, publish: 'telemetry', quantity: 'temperature', unit: 'degC' }),
      variable({ path: 'fuelTemperatureC', label: 'Core fuel temperature', kind: 'state', domain: 'thermal', writable: false, publish: 'telemetry', quantity: 'temperature', unit: 'degC' }),
      variable({ path: 'fuelLowerTemperatureC', label: 'Lower fuel temperature', kind: 'state', domain: 'thermal', writable: false, publish: 'telemetry', quantity: 'temperature', unit: 'degC' }),
      variable({ path: 'fuelMidTemperatureC', label: 'Mid-core fuel temperature', kind: 'state', domain: 'thermal', writable: false, publish: 'telemetry', quantity: 'temperature', unit: 'degC' }),
      variable({ path: 'fuelUpperTemperatureC', label: 'Upper fuel temperature', kind: 'state', domain: 'thermal', writable: false, publish: 'telemetry', quantity: 'temperature', unit: 'degC' }),
      variable({ path: 'fuelStoredEnergyMj', label: 'Fuel stored heat energy', kind: 'derived', domain: 'thermal', writable: false, publish: 'telemetry', quantity: 'energy', unit: 'MJ' }),
      variable({ path: 'decayHeatMw', label: 'Decay heat', kind: 'state', domain: 'thermal', writable: false, publish: 'telemetry', quantity: 'power', unit: 'MW' }),
      variable({ path: 'heatToCoolantMw', label: 'Heat to coolant', kind: 'derived', domain: 'thermal', writable: false, publish: 'telemetry', quantity: 'power', unit: 'MW' }),
    ],
  }),
  defineComponent({
    kind: 'reactorVessel' as ComponentKind,
    label: 'Reactor Vessel',
    ports: {
      coreThermal: { kind: 'thermal', direction: 'in' },
      lowerPlenum: { kind: 'hydraulicThermal', direction: 'out' },
      upperPlenum: { kind: 'hydraulicThermal', direction: 'in' },
      pressurizerSurge: { kind: 'hydraulicThermal', direction: 'bidirectional' },
    },
    parametersSchema: z.object({
      nominalPrimaryCoolantInventoryKg: z.number().finite().positive(),
      initialPrimaryCoolantInventoryFraction: normalized,
      primaryCoolantVolumeM3: z.number().finite().positive(),
      nominalPrimaryCoolantDensityKgPerM3: z.number().finite().positive(),
      effectiveBulkModulusMPa: z.number().finite().positive(),
      thermalExpansionCoefficientPerC: z.number().finite().nonnegative(),
      referencePrimaryCoolantTemperatureC: z.number().finite(),
      normalLetdownFlowKgPerS: z.number().finite().nonnegative().optional(),
    }),
    variables: [
      variable({ path: 'primaryCoolantInventoryKg', label: 'Primary coolant inventory', kind: 'state', domain: 'hydraulic', writable: false, publish: 'telemetry', quantity: 'mass', unit: 'kg' }),
      variable({ path: 'primaryCoolantInventoryDeviationKg', label: 'Primary coolant inventory deviation', kind: 'derived', domain: 'hydraulic', writable: false, publish: 'telemetry', quantity: 'massDelta', unit: 'kg' }),
      variable({ path: 'meanPrimaryCoolantTemperatureC', label: 'Mean primary coolant temperature', kind: 'derived', domain: 'thermal', writable: false, publish: 'telemetry', quantity: 'temperature', unit: 'degC' }),
      variable({ path: 'compressibilityPressureBiasMPa', label: 'Primary compressibility pressure bias', kind: 'derived', domain: 'thermal', writable: false, publish: 'telemetry', quantity: 'pressureDelta', unit: 'MPa' }),
      variable({ path: 'thermalExpansionPressureBiasMPa', label: 'Primary thermal expansion pressure bias', kind: 'derived', domain: 'thermal', writable: false, publish: 'telemetry', quantity: 'pressureDelta', unit: 'MPa' }),
      variable({ path: 'primaryPressureBiasMPa', label: 'Primary pressure inventory bias', kind: 'derived', domain: 'thermal', writable: false, publish: 'telemetry', quantity: 'pressureDelta', unit: 'MPa' }),
      variable({ path: 'chargingFlowKgPerS', label: 'Primary charging flow', kind: 'derived', domain: 'hydraulic', writable: false, publish: 'telemetry', quantity: 'flowRate', unit: 'kg/s' }),
      variable({ path: 'letdownFlowKgPerS', label: 'Primary letdown flow', kind: 'derived', domain: 'hydraulic', writable: false, publish: 'telemetry', quantity: 'flowRate', unit: 'kg/s' }),
      variable({ path: 'reliefOutflowKgPerS', label: 'Primary relief outflow', kind: 'derived', domain: 'hydraulic', writable: false, publish: 'telemetry', quantity: 'flowRate', unit: 'kg/s' }),
      variable({ path: 'primaryLeakFlowKgPerS', label: 'Primary coolant boundary leak flow', kind: 'derived', domain: 'hydraulic', writable: false, publish: 'telemetry', quantity: 'flowRate', unit: 'kg/s' }),
      variable({ path: 'tubeLeakFlowKgPerS', label: 'Primary-to-secondary tube leak flow', kind: 'derived', domain: 'hydraulic', writable: false, publish: 'telemetry', quantity: 'flowRate', unit: 'kg/s' }),
      variable({ path: 'netInventoryFlowKgPerS', label: 'Primary inventory net flow', kind: 'derived', domain: 'hydraulic', writable: false, publish: 'telemetry', quantity: 'flowRateDelta', unit: 'kg/s' }),
    ],
  }),
  defineComponent({
    kind: 'processHeader' as ComponentKind,
    label: 'Process Header',
    ports: {
      inletA: { kind: 'hydraulicThermal', direction: 'in' },
      inletB: { kind: 'hydraulicThermal', direction: 'in' },
      inletC: { kind: 'hydraulicThermal', direction: 'in' },
      inletD: { kind: 'hydraulicThermal', direction: 'in' },
      outletA: { kind: 'hydraulicThermal', direction: 'out' },
      outletB: { kind: 'hydraulicThermal', direction: 'out' },
      outletC: { kind: 'hydraulicThermal', direction: 'out' },
      outletD: { kind: 'hydraulicThermal', direction: 'out' },
    },
    parametersSchema: z.object({
      initialTemperatureC: z.number().finite().optional(),
      initialPressureMPa: z.number().finite().positive().optional(),
    }).strict(),
    variables: headerVariables('Process header'),
  }),
  defineComponent({
    kind: 'processTank' as ComponentKind,
    label: 'Process Tank',
    ports: {
      inlet: { kind: 'hydraulicThermal', direction: 'in' },
      outlet: { kind: 'hydraulicThermal', direction: 'out' },
    },
    parametersSchema: z.object({
      nominalInventoryKg: z.number().finite().positive(),
      initialInventoryFraction: normalized,
      initialTemperatureC: z.number().finite(),
      makeupFlowKgPerS: z.number().finite().nonnegative(),
      maxOutletFlowKgPerS: z.number().finite().nonnegative(),
      thermalTimeConstantS: z.number().finite().positive().optional(),
    }).strict(),
    variables: [
      variable({ path: 'inventoryKg', label: 'Tank inventory', kind: 'state', domain: 'hydraulic', writable: false, publish: 'telemetry', quantity: 'mass', unit: 'kg' }),
      variable({ path: 'levelPercent', label: 'Tank level', kind: 'state', domain: 'hydraulic', writable: false, publish: 'telemetry', quantity: 'ratio', unit: 'percent' }),
      variable({ path: 'temperatureC', label: 'Tank temperature', kind: 'state', domain: 'thermal', writable: false, publish: 'telemetry', quantity: 'temperature', unit: 'degC' }),
      variable({ path: 'makeupFlowKgPerS', label: 'Tank makeup flow', kind: 'control', domain: 'control', writable: true, publish: 'telemetry', quantity: 'flowRate', unit: 'kg/s' }),
      variable({ path: 'availableOutletFlowKgPerS', label: 'Available outlet flow', kind: 'derived', domain: 'hydraulic', writable: false, publish: 'telemetry', quantity: 'flowRate', unit: 'kg/s' }),
    ],
  }),
  defineComponent({
    kind: 'processValve' as ComponentKind,
    label: 'Process Valve',
    ports: {
      inlet: { kind: 'hydraulicThermal', direction: 'in' },
      outlet: { kind: 'hydraulicThermal', direction: 'out' },
      demand: { kind: 'controlSignal', direction: 'in' },
    },
    parametersSchema: z.object({
      initialPositionFraction: normalized.optional(),
      strokeTimeConstantS: z.number().finite().positive().optional(),
    }).strict(),
    variables: valveVariables('Process valve'),
  }),
  defineComponent({
    kind: 'steamHeader' as ComponentKind,
    label: 'Steam Header',
    ports: {
      inletA: { kind: 'steam', direction: 'in' },
      inletB: { kind: 'steam', direction: 'in' },
      inletC: { kind: 'steam', direction: 'in' },
      inletD: { kind: 'steam', direction: 'in' },
      outletA: { kind: 'steam', direction: 'out' },
      outletB: { kind: 'steam', direction: 'out' },
      outletC: { kind: 'steam', direction: 'out' },
      outletD: { kind: 'steam', direction: 'out' },
    },
    parametersSchema: z.object({
      initialTemperatureC: z.number().finite().optional(),
      initialPressureMPa: z.number().finite().positive().optional(),
    }).strict(),
    variables: headerVariables('Steam header'),
  }),
  defineComponent({
    kind: 'steamValve' as ComponentKind,
    label: 'Steam Valve',
    ports: {
      inlet: { kind: 'steam', direction: 'in' },
      outlet: { kind: 'steam', direction: 'out' },
      demand: { kind: 'controlSignal', direction: 'in' },
    },
    parametersSchema: z.object({
      initialPositionFraction: normalized.optional(),
      strokeTimeConstantS: z.number().finite().positive().optional(),
    }).strict(),
    variables: valveVariables('Steam valve'),
  }),
  defineComponent({
    kind: 'pressurizer' as ComponentKind,
    label: 'Pressurizer',
    ports: {
      surgeLine: { kind: 'hydraulicThermal', direction: 'bidirectional' },
      sprayInlet: { kind: 'hydraulicThermal', direction: 'in' },
      reliefOutlet: { kind: 'hydraulicThermal', direction: 'out' },
      heaterPower: { kind: 'electricalAc', direction: 'in' },
    },
    parametersSchema: z.object({
      nominalPressureMPa: z.number().finite().positive(),
      nominalLevelPercent: normalized,
      nominalWaterInventoryKg: z.number().finite().positive(),
      nominalSteamMassKg: z.number().finite().positive().optional(),
      initialWaterTemperatureC: z.number().finite().optional(),
      initialSteamTemperatureC: z.number().finite().optional(),
      pressureTimeConstantS: z.number().finite().positive().optional(),
      thermalTimeConstantS: z.number().finite().positive().optional(),
      reliefSetpointMPa: z.number().finite().positive().optional(),
      reliefCapacityKgPerS: z.number().finite().nonnegative().optional(),
      sprayCondensationKgPerKg: z.number().finite().nonnegative().optional(),
      nominalWaterDensityKgPerM3: z.number().finite().positive().optional(),
    }),
    variables: [
      variable({ path: 'pressureMPa', label: 'Pressurizer pressure', kind: 'state', domain: 'thermal', writable: false, publish: 'telemetry', quantity: 'pressure', unit: 'MPa' }),
      variable({ path: 'levelPercent', label: 'Pressurizer level', kind: 'state', domain: 'hydraulic', writable: false, publish: 'telemetry', quantity: 'ratio', unit: 'percent' }),
      variable({ path: 'waterInventoryKg', label: 'Pressurizer water inventory', kind: 'state', domain: 'hydraulic', writable: false, publish: 'telemetry', quantity: 'mass', unit: 'kg' }),
      variable({ path: 'steamMassKg', label: 'Pressurizer steam mass', kind: 'state', domain: 'thermal', writable: false, publish: 'telemetry', quantity: 'mass', unit: 'kg' }),
      variable({ path: 'steamMassFlowKgPerS', label: 'Pressurizer steam net mass flow', kind: 'derived', domain: 'hydraulic', writable: false, publish: 'telemetry', quantity: 'flowRateDelta', unit: 'kg/s' }),
      variable({ path: 'steamVolumeM3', label: 'Pressurizer steam volume', kind: 'derived', domain: 'hydraulic', writable: false, publish: 'telemetry', quantity: 'volume', unit: 'm3' }),
      variable({ path: 'steamPressureMPa', label: 'Pressurizer steam pressure proxy', kind: 'derived', domain: 'thermal', writable: false, publish: 'telemetry', quantity: 'pressure', unit: 'MPa' }),
      variable({ path: 'pressureTargetMPa', label: 'Pressurizer pressure target', kind: 'derived', domain: 'thermal', writable: false, publish: 'telemetry', quantity: 'pressure', unit: 'MPa' }),
      variable({ path: 'waterInventoryBalanceResidualKg', label: 'Pressurizer water inventory balance residual', kind: 'derived', domain: 'hydraulic', writable: false, publish: 'telemetry', quantity: 'massDelta', unit: 'kg' }),
      variable({ path: 'steamMassBalanceResidualKg', label: 'Pressurizer steam mass balance residual', kind: 'derived', domain: 'hydraulic', writable: false, publish: 'telemetry', quantity: 'massDelta', unit: 'kg' }),
      variable({ path: 'waterTemperatureC', label: 'Pressurizer water temperature', kind: 'state', domain: 'thermal', writable: false, publish: 'telemetry', quantity: 'temperature', unit: 'degC' }),
      variable({ path: 'steamTemperatureC', label: 'Pressurizer steam temperature', kind: 'state', domain: 'thermal', writable: false, publish: 'telemetry', quantity: 'temperature', unit: 'degC' }),
      variable({ path: 'heaterPowerMw', label: 'Pressurizer heater power', kind: 'control', domain: 'control', writable: true, publish: 'telemetry', quantity: 'power', unit: 'MW' }),
      variable({ path: 'sprayFlowKgPerS', label: 'Pressurizer spray flow', kind: 'control', domain: 'control', writable: true, publish: 'telemetry', quantity: 'flowRate', unit: 'kg/s' }),
      variable({ path: 'reliefValvePositionFraction', label: 'Pressurizer relief valve position', kind: 'control', domain: 'control', writable: true, publish: 'telemetry', quantity: 'ratio', unit: 'fraction' }),
      variable({ path: 'reliefFlowKgPerS', label: 'Pressurizer relief flow', kind: 'derived', domain: 'hydraulic', writable: false, publish: 'telemetry', quantity: 'flowRate', unit: 'kg/s' }),
    ],
  }),
  topologyComponent('pressurizerHeaters', 'Pressurizer Heaters', {
    powerInlet: { kind: 'electricalAc', direction: 'in' },
    heatOutput: { kind: 'thermal', direction: 'out' },
  }),
  topologyComponent('generatorSink', 'Generator Sink', {
    electricalInput: { kind: 'electricalAc', direction: 'in' },
    electricalOutput: { kind: 'electricalAc', direction: 'out' },
  }),
  defineComponent({
    kind: 'steamGenerator' as ComponentKind,
    label: 'Steam Generator',
    ports: {
      primaryInlet: { kind: 'hydraulicThermal', direction: 'in' },
      primaryOutlet: { kind: 'hydraulicThermal', direction: 'out' },
      feedwaterInlet: { kind: 'hydraulicThermal', direction: 'in' },
      steamOutlet: { kind: 'steam', direction: 'out' },
      isolationSignal: { kind: 'logicSignal', direction: 'in' },
    },
    parametersSchema: z.object({
      nominalPressureMPa: z.number().finite().positive(),
      nominalLevelPercent: normalized,
      heatTransferCoefficientMwPerK: z.number().finite().positive(),
      initialPrimaryInletTemperatureC: z.number().finite().optional(),
      initialSecondaryTemperatureC: z.number().finite().optional(),
      nominalSecondaryInventoryKg: z.number().finite().positive().optional(),
      nominalSteamFlowKgPerS: z.number().finite().positive().optional(),
      recirculationRatio: z.number().finite().positive().optional(),
      primaryThermalTimeConstantS: z.number().finite().positive().optional(),
      secondaryThermalTimeConstantS: z.number().finite().positive().optional(),
      steamQualityTimeConstantS: z.number().finite().positive().optional(),
      steamPressureGainMPaPerKgS: z.number().finite().nonnegative().optional(),
      nominalSteamMassKg: z.number().finite().positive().optional(),
      voidFractionAtNominalBoiling: normalized.optional(),
      voidFractionTimeConstantS: z.number().finite().positive().optional(),
      swellLevelGainPercent: z.number().finite().nonnegative().optional(),
      pressureInventoryGainMPaPerFraction: z.number().finite().nonnegative().optional(),
      tubeMetalThermalCapacityMjPerK: z.number().finite().positive().optional(),
      tubeMetalInitialTemperatureC: z.number().finite().optional(),
      tubeLeakFlowCoefficientKgPerSPerSqrtMPa: z.number().finite().nonnegative().optional(),
      tubeLeakRadiationGainMSvPerHPerKgS: z.number().finite().nonnegative().optional(),
      tubeLeakRadiationTimeConstantS: z.number().finite().positive().optional(),
    }),
    variables: [
      variable({ path: 'levelPercent', label: 'Steam generator level', kind: 'state', domain: 'hydraulic', writable: false, publish: 'telemetry', quantity: 'ratio', unit: 'percent' }),
      variable({ path: 'pressureMPa', label: 'Steam generator pressure', kind: 'state', domain: 'thermal', writable: false, publish: 'telemetry', quantity: 'pressure', unit: 'MPa' }),
      variable({ path: 'heatTransferMw', label: 'Heat transfer', kind: 'derived', domain: 'thermal', writable: false, publish: 'telemetry', quantity: 'power', unit: 'MW' }),
      variable({ path: 'primaryInletTemperatureC', label: 'Primary inlet temperature', kind: 'state', domain: 'thermal', writable: false, publish: 'telemetry', quantity: 'temperature', unit: 'degC' }),
      variable({ path: 'primaryOutletTemperatureC', label: 'Primary outlet temperature', kind: 'state', domain: 'thermal', writable: false, publish: 'telemetry', quantity: 'temperature', unit: 'degC' }),
      variable({ path: 'tubeMetalTemperatureC', label: 'Tube metal temperature', kind: 'state', domain: 'thermal', writable: false, publish: 'telemetry', quantity: 'temperature', unit: 'degC' }),
      variable({ path: 'secondaryTemperatureC', label: 'Secondary temperature', kind: 'state', domain: 'thermal', writable: false, publish: 'telemetry', quantity: 'temperature', unit: 'degC' }),
      variable({ path: 'steamFlowKgPerS', label: 'Steam production', kind: 'derived', domain: 'hydraulic', writable: false, publish: 'telemetry', quantity: 'flowRate', unit: 'kg/s' }),
      variable({ path: 'boilingRateKgPerS', label: 'Secondary boiling rate', kind: 'derived', domain: 'hydraulic', writable: false, publish: 'telemetry', quantity: 'flowRate', unit: 'kg/s' }),
      variable({ path: 'feedwaterFlowKgPerS', label: 'Feedwater inflow', kind: 'derived', domain: 'hydraulic', writable: false, publish: 'telemetry', quantity: 'flowRate', unit: 'kg/s' }),
      variable({ path: 'steamOutflowKgPerS', label: 'Steam outlet flow', kind: 'derived', domain: 'hydraulic', writable: false, publish: 'telemetry', quantity: 'flowRate', unit: 'kg/s' }),
      variable({ path: 'steamQualityFraction', label: 'Steam quality', kind: 'derived', domain: 'thermal', writable: false, publish: 'telemetry', quantity: 'ratio', unit: 'fraction' }),
      variable({ path: 'secondaryInventoryKg', label: 'Secondary inventory', kind: 'state', domain: 'hydraulic', writable: false, publish: 'telemetry', quantity: 'mass', unit: 'kg' }),
      variable({ path: 'collapsedLevelPercent', label: 'Collapsed water level', kind: 'state', domain: 'hydraulic', writable: false, publish: 'telemetry', quantity: 'ratio', unit: 'percent' }),
      variable({ path: 'voidFraction', label: 'Secondary void fraction', kind: 'state', domain: 'thermal', writable: false, publish: 'telemetry', quantity: 'ratio', unit: 'fraction' }),
      variable({ path: 'swellLevelPercent', label: 'Void swell level contribution', kind: 'derived', domain: 'hydraulic', writable: false, publish: 'telemetry', quantity: 'ratio', unit: 'percent' }),
      variable({ path: 'steamMassKg', label: 'Steam space mass proxy', kind: 'state', domain: 'thermal', writable: false, publish: 'telemetry', quantity: 'mass', unit: 'kg' }),
      variable({ path: 'pressureTargetMPa', label: 'Steam generator pressure target', kind: 'derived', domain: 'thermal', writable: false, publish: 'telemetry', quantity: 'pressure', unit: 'MPa' }),
      variable({ path: 'steamMassPressureBiasMPa', label: 'Steam mass pressure contribution', kind: 'derived', domain: 'thermal', writable: false, publish: 'telemetry', quantity: 'pressureDelta', unit: 'MPa' }),
      variable({ path: 'temperaturePressureBiasMPa', label: 'Secondary temperature pressure contribution', kind: 'derived', domain: 'thermal', writable: false, publish: 'telemetry', quantity: 'pressureDelta', unit: 'MPa' }),
      variable({ path: 'inventoryPressureBiasMPa', label: 'Secondary inventory pressure contribution', kind: 'derived', domain: 'thermal', writable: false, publish: 'telemetry', quantity: 'pressureDelta', unit: 'MPa' }),
      variable({ path: 'secondaryInventoryBalanceResidualKg', label: 'Secondary inventory balance residual', kind: 'derived', domain: 'hydraulic', writable: false, publish: 'telemetry', quantity: 'massDelta', unit: 'kg' }),
      variable({ path: 'steamMassBalanceResidualKg', label: 'Steam mass balance residual', kind: 'derived', domain: 'hydraulic', writable: false, publish: 'telemetry', quantity: 'massDelta', unit: 'kg' }),
      variable({ path: 'boilingEnergyResidualMw', label: 'Boiling energy balance residual', kind: 'derived', domain: 'thermal', writable: false, publish: 'telemetry', quantity: 'powerDelta', unit: 'MW' }),
      variable({ path: 'tubeLeakFraction', label: 'Tube leak fraction', kind: 'control', domain: 'control', writable: true, publish: 'telemetry', quantity: 'ratio', unit: 'fraction' }),
      variable({ path: 'primaryToSecondaryLeakKgPerS', label: 'Primary-to-secondary leak flow', kind: 'derived', domain: 'hydraulic', writable: false, publish: 'telemetry', quantity: 'flowRate', unit: 'kg/s' }),
      variable({ path: 'secondaryRadiationMSvPerH', label: 'Secondary radiation', kind: 'derived', domain: 'radiological', writable: false, publish: 'telemetry', quantity: 'radiationDoseRate', unit: 'mSv/h' }),
    ],
  }),
  defineComponent({
    kind: 'centrifugalPump' as ComponentKind,
    label: 'Centrifugal Pump',
    ports: {
      inlet: { kind: 'hydraulicThermal', direction: 'in' },
      outlet: { kind: 'hydraulicThermal', direction: 'out' },
      speedDemand: { kind: 'controlSignal', direction: 'in' },
      power: { kind: 'electricalAc', direction: 'in' },
    },
    parametersSchema: z.object({
      nominalFlowKgPerS: z.number().finite().positive(),
      nominalHeadPa: z.number().finite().positive(),
      primaryLoopId: z.string().min(1).regex(/^[a-zA-Z0-9][a-zA-Z0-9._:-]*$/).optional(),
      initialRunning: z.boolean().optional(),
      flowTimeConstantS: z.number().finite().positive().optional(),
      maxFlowRampKgPerS2: z.number().finite().positive().optional(),
      loopInertiaTimeConstantS: z.number().finite().positive().optional(),
      coastdownTimeConstantS: z.number().finite().positive().optional(),
      loopResistanceCoefficient: z.number().finite().nonnegative().optional(),
      minimumNaturalCirculationFlowKgPerS: z.number().finite().nonnegative().optional(),
    }),
    variables: [
      variable({ path: 'running', label: 'Running', kind: 'discrete', domain: 'control', writable: true, publish: 'telemetry', quantity: 'boolean', unit: 'boolean' }),
      variable({ path: 'speedFraction', label: 'Speed', kind: 'control', domain: 'control', writable: true, publish: 'telemetry', quantity: 'ratio', unit: 'fraction' }),
      variable({ path: 'flowKgPerS', label: 'Flow', kind: 'derived', domain: 'hydraulic', writable: false, publish: 'telemetry', quantity: 'flowRate', unit: 'kg/s' }),
      variable({ path: 'developedHeadPa', label: 'Developed head', kind: 'derived', domain: 'hydraulic', writable: false, publish: 'telemetry', quantity: 'head', unit: 'Pa' }),
      variable({ path: 'loopFlowTargetKgPerS', label: 'Primary loop target flow', kind: 'derived', domain: 'hydraulic', writable: false, publish: 'telemetry', quantity: 'flowRate', unit: 'kg/s' }),
      variable({ path: 'loopFlowKgPerS', label: 'Primary loop flow', kind: 'state', domain: 'hydraulic', writable: false, publish: 'telemetry', quantity: 'flowRate', unit: 'kg/s' }),
    ],
  }),
  defineComponent({
    kind: 'feedwaterSource' as ComponentKind,
    label: 'Feedwater Source',
    ports: {
      outlet: { kind: 'hydraulicThermal', direction: 'out' },
      flowDemand: { kind: 'controlSignal', direction: 'in' },
    },
    parametersSchema: z.object({
      nominalFlowKgPerS: z.number().finite().positive(),
      temperatureC: z.number().finite(),
    }),
    variables: [
      variable({ path: 'flowKgPerS', label: 'Feedwater flow', kind: 'state', domain: 'hydraulic', writable: true, publish: 'telemetry', quantity: 'flowRate', unit: 'kg/s' }),
      variable({ path: 'temperatureC', label: 'Feedwater temperature', kind: 'state', domain: 'thermal', writable: false, publish: 'telemetry', quantity: 'temperature', unit: 'degC' }),
    ],
  }),
  defineComponent({
    kind: 'turbineLoadSink' as ComponentKind,
    label: 'Turbine Load Sink',
    ports: {
      steamInlet: { kind: 'steam', direction: 'in' },
      exhaustSteamOutlet: { kind: 'steam', direction: 'out' },
      loadDemand: { kind: 'controlSignal', direction: 'in' },
      generatorOutput: { kind: 'electricalAc', direction: 'out' },
    },
    parametersSchema: z.object({
      nominalElectricMw: z.number().finite().positive(),
      initialLoadFraction: normalized,
      nominalSteamFlowKgPerS: z.number().finite().positive(),
      electricalTimeConstantS: z.number().finite().positive().optional(),
      exhaustTemperatureAtFullLoadC: z.number().finite().optional(),
      exhaustTemperatureAtNoLoadC: z.number().finite().optional(),
    }),
    variables: [
      variable({ path: 'electricMw', label: 'Electrical output', kind: 'derived', domain: 'electrical', writable: false, publish: 'telemetry', quantity: 'power', unit: 'MW' }),
      variable({ path: 'loadFraction', label: 'Load demand', kind: 'control', domain: 'control', writable: true, publish: 'telemetry', quantity: 'ratio', unit: 'fraction' }),
      variable({ path: 'steamFlowKgPerS', label: 'Turbine steam flow', kind: 'derived', domain: 'hydraulic', writable: false, publish: 'telemetry', quantity: 'flowRate', unit: 'kg/s' }),
      variable({ path: 'steamDemandKgPerS', label: 'Turbine steam demand', kind: 'derived', domain: 'hydraulic', writable: false, publish: 'telemetry', quantity: 'flowRate', unit: 'kg/s' }),
      variable({ path: 'steamAvailabilityFraction', label: 'Turbine steam availability', kind: 'derived', domain: 'thermal', writable: false, publish: 'telemetry', quantity: 'ratio', unit: 'fraction' }),
      variable({ path: 'exhaustTemperatureC', label: 'Turbine exhaust temperature', kind: 'derived', domain: 'thermal', writable: false, publish: 'telemetry', quantity: 'temperature', unit: 'degC' }),
    ],
  }),
  defineComponent({
    kind: 'condenserSink' as ComponentKind,
    label: 'Condenser Sink',
    ports: {
      steamInlet: { kind: 'steam', direction: 'in' },
      condensateOutlet: { kind: 'hydraulicThermal', direction: 'out' },
      coolingWater: { kind: 'hydraulicThermal', direction: 'in' },
    },
    parametersSchema: z.object({
      coolingWaterTemperatureC: z.number().finite(),
      nominalSteamFlowKgPerS: z.number().finite().positive(),
      condensateApproachTemperatureK: z.number().finite().nonnegative(),
      nominalCondensateInventoryKg: z.number().finite().positive(),
      initialCondensateInventoryFraction: normalized,
      maxCondensateOutletFlowKgPerS: z.number().finite().nonnegative(),
      condenserThermalTimeConstantS: z.number().finite().positive().optional(),
      exhaustCondensationTemperatureC: z.number().finite().optional(),
    }),
    variables: [
      variable({ path: 'steamFlowKgPerS', label: 'Condenser steam flow', kind: 'derived', domain: 'hydraulic', writable: false, publish: 'telemetry', quantity: 'flowRate', unit: 'kg/s' }),
      variable({ path: 'condensateProductionKgPerS', label: 'Condensate production', kind: 'derived', domain: 'hydraulic', writable: false, publish: 'telemetry', quantity: 'flowRate', unit: 'kg/s' }),
      variable({ path: 'heatRejectedMw', label: 'Condenser heat rejected', kind: 'derived', domain: 'thermal', writable: false, publish: 'telemetry', quantity: 'power', unit: 'MW' }),
      variable({ path: 'condensateInventoryKg', label: 'Condensate inventory', kind: 'state', domain: 'hydraulic', writable: false, publish: 'telemetry', quantity: 'mass', unit: 'kg' }),
      variable({ path: 'condensateLevelPercent', label: 'Condensate level', kind: 'state', domain: 'hydraulic', writable: false, publish: 'telemetry', quantity: 'ratio', unit: 'percent' }),
      variable({ path: 'availableCondensateOutletFlowKgPerS', label: 'Available condensate outlet flow', kind: 'derived', domain: 'hydraulic', writable: false, publish: 'telemetry', quantity: 'flowRate', unit: 'kg/s' }),
      variable({ path: 'condensateTemperatureC', label: 'Condensate temperature', kind: 'state', domain: 'thermal', writable: false, publish: 'telemetry', quantity: 'temperature', unit: 'degC' }),
      variable({ path: 'backPressurePa', label: 'Condenser back pressure', kind: 'derived', domain: 'thermal', writable: false, publish: 'telemetry', quantity: 'pressure', unit: 'Pa' }),
    ],
  }),
]

export const processPlantComponentRegistry: ReadonlyMap<ComponentKind, ComponentDefinition> = new Map(
  processPlantComponentDefinitions.map(definition => [definition.kind, definition]),
)
